.gitignore
LICENSE
README.md
pom.xml

Wdyt? This will now work .. I can merge and cut a release now

Central deployment readiness

---

.gitignore
README.md
src/main/java/com/walmartlabs/x12/dex/dx894/DefaultDex894Parser.java
src/main/java/com/walmartlabs/x12/dex/dx894/DefaultDex894Validator.java
src/main/java/com/walmartlabs/x12/dex/dx894/Dex894Allowance.java
src/main/java/com/walmartlabs/x12/dex/dx894/Dex894Item.java
src/main/java/com/walmartlabs/x12/dex/dx894/Dex894TransactionSet.java
src/main/java/com/walmartlabs/x12/dex/dx894/InvoiceType.java
src/main/java/com/walmartlabs/x12/dex/dx894/ProductQualifier.java
src/test/java/com/walmartlabs/x12/dex/dx894/DefaultDex894ParserTest.java
src/test/java/com/walmartlabs/x12/dex/dx894/DefaultDex894ParserTransactionTest.java
src/test/java/com/walmartlabs/x12/dex/dx894/ProductQualifierTest.java

PR for #7 handling the parsing 
a separate PR will be added for validations

Add parsing for G72 and G84 segments

---

README.md
src/main/java/com/walmartlabs/x12/X12Parser.java
src/main/java/com/walmartlabs/x12/dex/dx894/DefaultDex894Parser.java
src/test/java/com/walmartlabs/x12/X12ParserTest.java
src/test/java/com/walmartlabs/x12/dex/dx894/DefaultDex894ParserTest.java

in prep for ASN wanted to move some capability to interface

Refactor to allow for sharing asterisk parsing w/ more parsers

---

src/test/java/com/walmartlabs/x12/checksum/Crc16Test.java

a test to verify CRC 16 works (per #18)

Add test for CRC16 check on full transaction

---

src/main/java/com/walmartlabs/x12/dex/dx894/DefaultDex894Parser.java
src/main/java/com/walmartlabs/x12/dex/dx894/Dex894TransactionSet.java
src/test/java/com/walmartlabs/x12/dex/dx894/DefaultDex894ParseValidateTest.java

capture full DEX transaction for integrity check 

---

src/main/java/com/walmartlabs/x12/checksum/CyclicRedundancyCheck.java
src/main/java/com/walmartlabs/x12/checksum/DefaultCrc16.java
src/main/java/com/walmartlabs/x12/dex/dx894/DefaultDex894Validator.java
src/test/java/com/walmartlabs/x12/checksum/DefaultCrc16Test.java
src/test/java/com/walmartlabs/x12/dex/dx894/DefaultDex894ValidatorTest.java

Issue #26 padding the CRC value for DEX

Issue #26 padding the CRC value for DEX

---

src/main/java/com/walmartlabs/x12/dex/dx894/DefaultDex894Parser.java
src/main/java/com/walmartlabs/x12/dex/dx894/DefaultDex894Validator.java
src/main/java/com/walmartlabs/x12/dex/dx894/Dex894Item.java
src/test/java/com/walmartlabs/x12/dex/dx894/DefaultDex894ParseValidateTest.java
src/test/java/com/walmartlabs/x12/dex/dx894/DefaultDex894ParserTest.java
src/test/java/com/walmartlabs/x12/dex/dx894/DefaultDex894ValidatorTest.java

Issue #31 support multiple G72

---

src/main/java/com/walmartlabs/x12/dex/dx894/DefaultDex894Validator.java
src/test/java/com/walmartlabs/x12/dex/dx894/DefaultDex894ValidatorTest.java

[Issue-37] Add fix for null DXE02 element

---

src/itest/java/BatchFileParser.java

a utility to test large batches of files 
figured would offer it for others too
it is in a special directory `src/itest/java` to avoid making it part of the major effort

Batch Parsing util

---

src/main/java/com/walmartlabs/x12/asn856/AsnTransactionSet.java
src/main/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParser.java
src/main/java/com/walmartlabs/x12/asn856/Item.java
src/main/java/com/walmartlabs/x12/asn856/Pack.java
src/main/java/com/walmartlabs/x12/asn856/Shipment.java
src/main/java/com/walmartlabs/x12/asn856/Tare.java
src/main/java/com/walmartlabs/x12/util/X12ParsingUtil.java
src/test/java/com/walmartlabs/x12/asn856/Asn856ParserTest.java
src/test/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParserTest.java

Partial implementation of the ASN transaction set parser (#43)
- flush out the implementation approach

ASN transaction set parsing (partial implementation)

---

src/main/java/com/walmartlabs/x12/X12Segment.java
src/test/java/com/walmartlabs/x12/X12SegmentTest.java
src/test/java/com/walmartlabs/x12/dex/dx894/DefaultDex894ParserTransactionTest.java
src/test/java/sample/parser/SampleX12Parser.java
src/test/java/sample/parser/SampleX12Validator.java
src/test/java/sample/parser/X12SampleTest.java

fix alphanumeric delimiter in X12Segment

---

src/main/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParser.java
src/main/java/com/walmartlabs/x12/asn856/Shipment.java
src/main/java/com/walmartlabs/x12/common/segment/N1PartyIdentification.java
src/main/java/com/walmartlabs/x12/common/segment/N3PartyLocation.java
src/main/java/com/walmartlabs/x12/common/segment/N4GeographicLocation.java
src/main/java/com/walmartlabs/x12/common/segment/TD1CarrierDetails.java
src/main/java/com/walmartlabs/x12/common/segment/TD3CarrierDetails.java
src/main/java/com/walmartlabs/x12/common/segment/TD5CarrierDetails.java
src/main/java/com/walmartlabs/x12/common/segment/parser/N1PartyIdentificationParser.java
src/main/java/com/walmartlabs/x12/common/segment/parser/N3PartyLocationParser.java
src/main/java/com/walmartlabs/x12/common/segment/parser/N4GeographicLocationParser.java
src/main/java/com/walmartlabs/x12/common/segment/parser/TD1CarrierDetailsParser.java
src/main/java/com/walmartlabs/x12/common/segment/parser/TD3CarrierDetailsParser.java
src/main/java/com/walmartlabs/x12/common/segment/parser/TD5CarrierDetailsParser.java
src/test/java/com/walmartlabs/x12/common/segment/parser/N1PartyIdentificationParserTest.java
src/test/java/com/walmartlabs/x12/common/segment/parser/TD1CarrierDetailsParserTest.java
src/test/java/com/walmartlabs/x12/common/segment/parser/TD3CarrierDetailsParserTest.java
src/test/java/com/walmartlabs/x12/common/segment/parser/TD5CarrierDetailsParserTest.java

Part of implementation for #43

add N1 segment & parser

---

src/main/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParser.java
src/main/java/com/walmartlabs/x12/asn856/Item.java
src/main/java/com/walmartlabs/x12/asn856/Order.java
src/main/java/com/walmartlabs/x12/asn856/Pack.java
src/main/java/com/walmartlabs/x12/asn856/Shipment.java
src/main/java/com/walmartlabs/x12/util/TriConsumer.java
src/test/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParserEntireTxSetTest.java

part of #43 
worked out approach to handling the segments associated with each loop
still need to flush out how to handle loops that are a child to order 
complexity increases. due to fact that the sequencing can vary
- T, P, I
- T, I, P
- P, I
- I, P
- I

template for looping thru HL segments

---

AddingParsers.md
README.md

Update Gozer Documents (part 1)

---

src/main/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParser.java
src/main/java/com/walmartlabs/x12/asn856/Item.java
src/main/java/com/walmartlabs/x12/asn856/Pack.java
src/main/java/com/walmartlabs/x12/asn856/Shipment.java
src/test/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParserEntireTxSetTest.java
src/test/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParserPerishableTest.java

Part 1 for supporting Perishable ASN (#96)

Add support for Perishable Pack (ASN)

---

src/main/java/com/walmartlabs/x12/asn856/Batch.java
src/main/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParser.java
src/test/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParserPerishableTest.java
src/test/java/com/walmartlabs/x12/util/split/X12TransactionSplitterTest.java

Adds support for the Batch HL  (#98 )

Add support for Perishable Batch Loop (ASN)

---

src/main/java/com/walmartlabs/x12/asn856/Batch.java
src/main/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParser.java
src/main/java/com/walmartlabs/x12/asn856/Shipment.java
src/main/java/com/walmartlabs/x12/common/segment/parser/DTMDateTimeReferenceParser.java
src/test/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParserEntireTxSetTest.java
src/test/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParserPerishableTest.java
src/test/java/com/walmartlabs/x12/common/segment/parser/DTMDateTimeReferenceParserTest.java

Add support for DTM to the ASN (#43)

Add the DTM segment to ASN parser

---

src/main/java/com/walmartlabs/x12/asn856/Batch.java
src/main/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParser.java
src/main/java/com/walmartlabs/x12/asn856/Shipment.java
src/test/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParserEntireTxSetTest.java
src/test/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParserPerishableTest.java

Complete adding support for REF to the ASN (#43)

Add the REF segment to ASN parser

---

src/main/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParser.java
src/main/java/com/walmartlabs/x12/asn856/Pack.java
src/main/java/com/walmartlabs/x12/common/segment/TD1CarrierDetail.java
src/main/java/com/walmartlabs/x12/common/segment/parser/TD1CarrierDetailParser.java
src/test/java/com/walmartlabs/x12/asn856/DefaultAsn856TransactionSetParserPerishableTest.java
src/test/java/com/walmartlabs/x12/common/segment/parser/TD1CarrierDetailParserTest.java

Add the TD1 to pack (ASN)

---

src/main/java/com/walmartlabs/x12/X12ParsingUtil.java
src/main/java/com/walmartlabs/x12/standard/txset/asn856/AsnTransactionSet.java
src/main/java/com/walmartlabs/x12/standard/txset/asn856/DefaultAsn856TransactionSetParser.java
src/test/java/com/walmartlabs/x12/standard/txset/asn856/DefaultAsn856TransactionSetParserTest.java

Handle Looping errors w/o Exception (part 1)

---

src/main/java/com/walmartlabs/x12/standard/txset/asn856/DefaultAsn856TransactionSetParser.java
src/main/java/com/walmartlabs/x12/standard/txset/asn856/loop/Order.java
src/main/java/com/walmartlabs/x12/standard/txset/asn856/loop/Pack.java
src/test/java/com/walmartlabs/x12/standard/txset/asn856/DefaultAsn856TransactionSetParserTest.java

Add N1 support to Order loop & N1 as list on Pack for ASN 856 
